create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  company text,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists leads_created_at_idx on public.leads(created_at desc);
create index if not exists leads_email_idx on public.leads(email);

alter table public.leads enable row level security;

-- The API writes with the Supabase service-role key, server-side only.
-- No anon/public insert policy is intentionally created.
